[[watch]]
name = "build site"
path = "templates"
command = "blades build"

[[watch]]
name = "build site"
path = "content"
command = "blades build"

[[watch]]
name = "build site"
path = "Blades.toml"
command = "blades build"

[[watch]]
name = "build sass"
path = "sass"
command = "sassc -t compressed sass/style.scss public/assets/style.css"

